server:
  port: 8080

spring:
  application:
    name: weather-station


harvester:
  url: http://80.211.242.104:8080
  token: ${BASIC_TOKEN}
station:
  basic-cron: "0 */5 * * * *"
  air-cron: "20 */5 * * * *"

management:
  endpoint:
    restart:
      enabled: true